In [1]:
import json

In [4]:
x='{"name":"john","age":30,"city":"new york"}'
y=json.loads(x)
print(y)

{'name': 'john', 'age': 30, 'city': 'new york'}


In [3]:
print(y["age"])

30


In [5]:
#convert from python to JSON

In [6]:
import json

In [7]:
x={"name":"John","age":30,"city":"new york"}

In [8]:
y=json.dumps(x)

In [9]:
print(y)

{"name": "John", "age": 30, "city": "new york"}


In [10]:
#convert python objects to json

In [11]:
import json

In [16]:
print(json.dumps({"name":"John","age":30}))

{"name": "John", "age": 30}


In [13]:
print(json.dumps(["apple","bananas"]))

["apple", "bananas"]


In [15]:
print(json.dumps(("apple","bananas")))

["apple", "bananas"]


In [19]:
print(json.dumps(42))

42


In [20]:
print(json.dumps(31.76))

31.76


In [21]:
print(json.dumps(True))

true


In [22]:
import json

In [23]:
x={
    "name":"John",
    "age":30,
    "married":True,
    "divorced":False,
    "children":("Ann","Billy"),
    "pets":None,
    "cats":[
        {"model":"BMW 230","mpg":27.5},
        {"model":"Ford Edge","mpg":24.01}
    ]
}

In [24]:
print(json.dumps(x))

{"name": "John", "age": 30, "married": true, "divorced": false, "children": ["Ann", "Billy"], "pets": null, "cats": [{"model": "BMW 230", "mpg": 27.5}, {"model": "Ford Edge", "mpg": 24.01}]}


In [29]:
json.dumps(x,indent=3)

'{\n   "name": "John",\n   "age": 30,\n   "married": true,\n   "divorced": false,\n   "children": [\n      "Ann",\n      "Billy"\n   ],\n   "pets": null,\n   "cats": [\n      {\n         "model": "BMW 230",\n         "mpg": 27.5\n      },\n      {\n         "model": "Ford Edge",\n         "mpg": 24.01\n      }\n   ]\n}'

In [27]:
json.dumps(x,indent=4,separators=(",",": "))

'{\n    "name": "John",\n    "age": 30,\n    "married": true,\n    "divorced": false,\n    "children": [\n        "Ann",\n        "Billy"\n    ],\n    "pets": null,\n    "cats": [\n        {\n            "model": "BMW 230",\n            "mpg": 27.5\n        },\n        {\n            "model": "Ford Edge",\n            "mpg": 24.01\n        }\n    ]\n}'

In [28]:
json.dumps(x, indent=4,sort_keys=True)

'{\n    "age": 30,\n    "cats": [\n        {\n            "model": "BMW 230",\n            "mpg": 27.5\n        },\n        {\n            "model": "Ford Edge",\n            "mpg": 24.01\n        }\n    ],\n    "children": [\n        "Ann",\n        "Billy"\n    ],\n    "divorced": false,\n    "married": true,\n    "name": "John",\n    "pets": null\n}'

In [30]:
import re

In [46]:
txt="The rain in spain"
x=re.search("ai",txt)
print(x)

<re.Match object; span=(5, 7), match='ai'>


In [33]:
len(txt)

17

In [41]:
txt="The rain in Spain"
x=re.sub("\s","9 ",txt,2)
print(x)

The9 rain9 in Spain


In [47]:
dir(re)

['A',
 'ASCII',
 'DEBUG',
 'DOTALL',
 'I',
 'IGNORECASE',
 'L',
 'LOCALE',
 'M',
 'MULTILINE',
 'Match',
 'Pattern',
 'RegexFlag',
 'S',
 'Scanner',
 'T',
 'TEMPLATE',
 'U',
 'UNICODE',
 'VERBOSE',
 'X',
 '_MAXCACHE',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '__version__',
 '_cache',
 '_compile',
 '_compile_repl',
 '_expand',
 '_locale',
 '_pickle',
 '_special_chars_map',
 '_subx',
 'compile',
 'copyreg',
 'enum',
 'error',
 'escape',
 'findall',
 'finditer',
 'fullmatch',
 'functools',
 'match',
 'purge',
 'search',
 'split',
 'sre_compile',
 'sre_parse',
 'sub',
 'subn',
 'template']

In [51]:
txt="The rain in Spain"
x=re.search(r"\bS\w+",txt)
print(x.span())
print(x.string)
print(x.group())

(12, 17)
The rain in Spain
Spain


In [57]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [58]:
arr=np.array((1,2,3,4,5))

In [59]:
arr

array([1, 2, 3, 4, 5])

In [60]:
arr=np.array(42)

In [65]:
# 2D array
b=np.array([[1,2,3],[4,5,6]])

In [72]:
print(arr)
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [77]:
# 3D array
arr=np.array([1,2,3,4,4],ndmin=5)
print(arr)


[[[[[1 2 3 4 4]]]]]


In [78]:
arr=np.array([1,2,3,4])

In [79]:
print(arr[0])

1


In [80]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,1])

2


In [81]:
a=np.array([[[1,2,3],[4,5,6]],[[7,8, 9],[10,11,12]]])

In [82]:
print(a[0,1,2])

6


In [83]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [84]:
print('Last elemnent from 2nd dim:',arr[1,-1])

Last elemnent from 2nd dim: 10


In [85]:
#slicing

In [88]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [92]:
print(arr[1:6:2])

[2 4 6]


In [91]:
arr[::2]

array([1, 3, 5, 7])

In [93]:
arr=np.array([[1,2,3,4,5],[6,7, 8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [99]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [101]:
print(arr[0:2,2])

[3 8]


In [102]:
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [104]:
#Data types in Numpy

In [105]:
arr=np.array([1,2,3,4,5])
print(arr.dtype)

int32


In [113]:
arr=np.array(['apple','banana','cherry'])
print(arr)
print(arr.dtype)

['apple' 'banana' 'cherry']
<U6


In [108]:
#creating  arrays with a defined data type

In [112]:
arr=np.array([1,2,3,4],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [114]:
arr=np.array([1,2,3,4],dtype='i4')
print(arr)

[1 2 3 4]


In [115]:
import numpy as np

arr=np.array(['a','2','3'],dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

In [120]:
#Change data type from float to integer by using 'i' as parameter value:
arr=np.array([1.6,2.1,3.1])
newarr=arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [122]:
#Change data type from float to integer by using int as parameter value:

arr=np.array([1.1,2.1,3.1])
newarr=arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [123]:
#change datatype from integer to boolean

In [124]:
arr=np.array([1,0,3])
newarr=arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


## numpy array vs copy

In [128]:
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [130]:
#Make a view, change the original array, and display both arrays:

In [133]:
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [134]:
arr=np.array([1,2,3,4,5])
x=arr.view()
x[0]=31
print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [135]:
# check if array owns its data

In [136]:
arr = np.array([1,2,3,4,5])
x=arr.copy() 
y=arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


## Numpy array shape

In [142]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [143]:
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print('shape of array:',arr.shape)

[[[[[1 2 3 4]]]]]
shape of array: (1, 1, 1, 1, 4)


In [147]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [148]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [149]:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr.reshape(2,4).base)

[1 2 3 4 5 6 7 8]


In [150]:
arr = np.array([1,2,3,4,5,6,7,8])
newarr=arr.reshape(2,2,-1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [151]:
#convert multidimention array into 1D array
arr=np.array([[1,2,3],[4,5,6]])
newarr=arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [152]:
#iterating array

In [153]:
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [154]:
arr=np.array([[1,2,3],[4,5,6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [155]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [158]:
for x in arr:
    for y in x:
        print(y)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [159]:
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [1]:
import pandas as pd

In [3]:
df=pd.read_csv('iris.csv')

In [5]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [6]:
pd.set_option('display.max_columns',85)
pd.set_option('display.max_rows',85)